simulate failure (TODO REVERT)

diff --git a/.github/workflows/lintdiff.yaml b/.github/workflows/lintdiff.yaml
--- a/.github/workflows/lintdiff.yaml
+++ b/.github/workflows/lintdiff.yaml
@@ -58,6 +58,9 @@ jobs:
           echo "⚠️ THIS IS A TEST ONLY FOR A LINTDIFF REPLACEMENT. IT'S OK IF THIS JOB FAILS. THIS WILL NOT BLOCK YOUR PR."
           echo "SEE OTHER LintDiff JOBS IN PR CHECKS FOR DEFINITIVE RESULTS."
 
+          # Simulate failure (revert)
+          exit 1
+
       - name: Prepend test notice to summary
         run: |
           temp_file=$(mktemp)
