Improve logging output

diff --git a/.github/workflows/lintdiff.yaml b/.github/workflows/lintdiff.yaml
--- a/.github/workflows/lintdiff.yaml
+++ b/.github/workflows/lintdiff.yaml
@@ -61,6 +61,10 @@ jobs:
             --compare-sha ${{ github.event.pull_request.head.sha }} \
             --out-file $GITHUB_STEP_SUMMARY
 
+          if [ $? -ne 0 ]; then
+            echo "LintDiff failed. See the summary for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
+          fi
+
           echo "⚠️ This check is testing a new version of 'Swagger LintDiff'."
           echo "⚠️ Failures are expected, and should be completely ignored by spec authors and reviewers."
           echo "⚠️ Meaningful results for this PR are are in required check 'Swagger LintDiff'."
