Fail the step when npm ci fails

diff --git a/eng/pipelines/templates/stages/archetype-spec-gen-sdk.yml b/eng/pipelines/templates/stages/archetype-spec-gen-sdk.yml
--- a/eng/pipelines/templates/stages/archetype-spec-gen-sdk.yml
+++ b/eng/pipelines/templates/stages/archetype-spec-gen-sdk.yml
@@ -246,6 +246,10 @@ stages:
           cd $(SpecRepoDirectory)
           echo "##[group]Run npm ci"
           npm ci
+          if [ "$?" -ne 0 ]; then
+            echo "##vso[task.logissue type=error]npm ci failed."
+            exit 1
+          fi
           echo "##[endgroup]"
           node $(SpecRepoDirectory)/eng/tools/spec-gen-sdk-runner/cmd/spec-gen-sdk-runner.js \
             --scp $(SpecRepoDirectory) \
